# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-16 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0002_auto_20181216_1317'),
        ('motion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motion',
            old_name='added',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='referral',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='motion',
            unique_together=set([('convention', 'identifier')]),
        ),
    ]
